#!/bin/bash
set -e

echo "CREATE DATABASE IF NOT EXISTS $DATABASE_NAME;" > $DB_INIT_SQL
echo "CREATE USER IF NOT EXISTS '$DATABASE_USER'@'%' IDENTIFIED BY '$DATABASE_PASSWORD';" >> $DB_INIT_SQL
echo "GRANT ALL PRIVILEGES ON *.* TO '$DATABASE_USER'@'%' IDENTIFIED BY '$DATABASE_PASSWORD' WITH GRANT OPTION;" >> $DB_INIT_SQL
echo "FLUSH PRIVILEGES;" >> $DB_INIT_SQL

sleep 5

mysql_install_db

mysqld
